; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "COLM ENROLLMENT SYSTEM"
#define MyAppVersion "2.0"
#define MyAppPublisher "College of Our Lady of Mercy Pulilan Foundaction Inc."
#define MyAppURL "https://www.facebook.com/colmpulilan/?fref=ts"
#define MyAppExeName "COLM ENROLLMENT SYSTEM.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{05AEEA29-B55A-4BF9-8FCC-3B4B5337B4BC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=C:\Users\System Admin\Documents\InnoSetup
OutputBaseFilename=COLM ENROLLMENT SYSTEM SETUP
SetupIconFile=C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\Resources\Logo.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\ARQUpdater.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\ARQUpdaterScript.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.vshost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.vshost.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.vshost.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\COLM ENROLLMENT SYSTEM.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\MdiTabControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\System Admin\Desktop\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\COLM ENROLLMENT SYSTEM\bin\x86\Release\Program Version.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

